--
-- PostgreSQL database dump
--

-- Dumped from database version 10.6
-- Dumped by pg_dump version 10.6

-- Started on 2018-12-06 23:01:00

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE telescrime;
--
-- TOC entry 2948 (class 1262 OID 16395)
-- Name: telescrime; Type: DATABASE; Schema: -; Owner: -
--

CREATE DATABASE telescrime WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'English_United Kingdom.1252' LC_CTYPE = 'English_United Kingdom.1252';


\connect telescrime

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 9 (class 2615 OID 16396)
-- Name: fencing; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA fencing;


--
-- TOC entry 1 (class 3079 OID 12924)
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- TOC entry 2952 (class 0 OID 0)
-- Dependencies: 1
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


--
-- TOC entry 2 (class 3079 OID 16467)
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA fencing;


--
-- TOC entry 2953 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION citext; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 198 (class 1259 OID 16397)
-- Name: bout; Type: TABLE; Schema: fencing; Owner: -
--

CREATE TABLE fencing.bout (
    bout_id integer NOT NULL,
    bout_date date,
    weapon_id integer
);


--
-- TOC entry 199 (class 1259 OID 16400)
-- Name: bout_bout_id_seq; Type: SEQUENCE; Schema: fencing; Owner: -
--

ALTER TABLE fencing.bout ALTER COLUMN bout_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME fencing.bout_bout_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 200 (class 1259 OID 16402)
-- Name: bout_fencer; Type: TABLE; Schema: fencing; Owner: -
--

CREATE TABLE fencing.bout_fencer (
    bout_id integer NOT NULL,
    fencer_id integer NOT NULL,
    hits smallint NOT NULL
);


--
-- TOC entry 201 (class 1259 OID 16405)
-- Name: fencer; Type: TABLE; Schema: fencing; Owner: -
--

CREATE TABLE fencing.fencer (
    fencer_id integer NOT NULL,
    name text
);


--
-- TOC entry 202 (class 1259 OID 16411)
-- Name: fencer_fencer_id_seq; Type: SEQUENCE; Schema: fencing; Owner: -
--

ALTER TABLE fencing.fencer ALTER COLUMN fencer_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME fencing.fencer_fencer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 208 (class 1259 OID 16555)
-- Name: principal; Type: TABLE; Schema: fencing; Owner: -
--

CREATE TABLE fencing.principal (
    id bigint NOT NULL,
    email fencing.citext,
    firstname character varying(255),
    lastname character varying(255),
    password character varying(255)
);


--
-- TOC entry 207 (class 1259 OID 16553)
-- Name: principal_id_seq; Type: SEQUENCE; Schema: fencing; Owner: -
--

ALTER TABLE fencing.principal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME fencing.principal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 16563)
-- Name: principal_role; Type: TABLE; Schema: fencing; Owner: -
--

CREATE TABLE fencing.principal_role (
    principal_id bigint NOT NULL,
    roles_id bigint NOT NULL
);


--
-- TOC entry 206 (class 1259 OID 16462)
-- Name: role; Type: TABLE; Schema: fencing; Owner: -
--

CREATE TABLE fencing.role (
    id bigint NOT NULL,
    role character varying(255) NOT NULL
);


--
-- TOC entry 205 (class 1259 OID 16460)
-- Name: role_id_seq; Type: SEQUENCE; Schema: fencing; Owner: -
--

ALTER TABLE fencing.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME fencing.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 16413)
-- Name: weapon; Type: TABLE; Schema: fencing; Owner: -
--

CREATE TABLE fencing.weapon (
    weapon_id integer NOT NULL,
    name text
);


--
-- TOC entry 204 (class 1259 OID 16419)
-- Name: weapon_weapon_id_seq; Type: SEQUENCE; Schema: fencing; Owner: -
--

ALTER TABLE fencing.weapon ALTER COLUMN weapon_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME fencing.weapon_weapon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2931 (class 0 OID 16397)
-- Dependencies: 198
-- Data for Name: bout; Type: TABLE DATA; Schema: fencing; Owner: -
--



--
-- TOC entry 2933 (class 0 OID 16402)
-- Dependencies: 200
-- Data for Name: bout_fencer; Type: TABLE DATA; Schema: fencing; Owner: -
--



--
-- TOC entry 2934 (class 0 OID 16405)
-- Dependencies: 201
-- Data for Name: fencer; Type: TABLE DATA; Schema: fencing; Owner: -
--

INSERT INTO fencing.fencer (fencer_id, name) OVERRIDING SYSTEM VALUE VALUES (1, 'Schmirgel McBirgelson');
INSERT INTO fencing.fencer (fencer_id, name) OVERRIDING SYSTEM VALUE VALUES (2, 'Prostetnic Vogon Jeltz');
INSERT INTO fencing.fencer (fencer_id, name) OVERRIDING SYSTEM VALUE VALUES (3, 'Arthur Dent');
INSERT INTO fencing.fencer (fencer_id, name) OVERRIDING SYSTEM VALUE VALUES (4, 'Ford Prefect');


--
-- TOC entry 2941 (class 0 OID 16555)
-- Dependencies: 208
-- Data for Name: principal; Type: TABLE DATA; Schema: fencing; Owner: -
--

INSERT INTO fencing.principal (id, email, firstname, lastname, password) VALUES (1, 'admin@test.com', 'Admin', 'Istrator', 'jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=');


--
-- TOC entry 2942 (class 0 OID 16563)
-- Dependencies: 209
-- Data for Name: principal_role; Type: TABLE DATA; Schema: fencing; Owner: -
--

INSERT INTO fencing.principal_role (principal_id, roles_id) VALUES (1, 1);
INSERT INTO fencing.principal_role (principal_id, roles_id) VALUES (1, 2);


--
-- TOC entry 2939 (class 0 OID 16462)
-- Dependencies: 206
-- Data for Name: role; Type: TABLE DATA; Schema: fencing; Owner: -
--

INSERT INTO fencing.role (id, role) VALUES (1, 'USER');
INSERT INTO fencing.role (id, role) VALUES (2, 'ADMIN');


--
-- TOC entry 2936 (class 0 OID 16413)
-- Dependencies: 203
-- Data for Name: weapon; Type: TABLE DATA; Schema: fencing; Owner: -
--

INSERT INTO fencing.weapon (weapon_id, name) OVERRIDING SYSTEM VALUE VALUES (1, 'Degen');


--
-- TOC entry 3005 (class 0 OID 0)
-- Dependencies: 199
-- Name: bout_bout_id_seq; Type: SEQUENCE SET; Schema: fencing; Owner: -
--

SELECT pg_catalog.setval('fencing.bout_bout_id_seq', 1, false);


--
-- TOC entry 3006 (class 0 OID 0)
-- Dependencies: 202
-- Name: fencer_fencer_id_seq; Type: SEQUENCE SET; Schema: fencing; Owner: -
--

SELECT pg_catalog.setval('fencing.fencer_fencer_id_seq', 4, true);


--
-- TOC entry 3007 (class 0 OID 0)
-- Dependencies: 207
-- Name: principal_id_seq; Type: SEQUENCE SET; Schema: fencing; Owner: -
--

SELECT pg_catalog.setval('fencing.principal_id_seq', 1, false);


--
-- TOC entry 3008 (class 0 OID 0)
-- Dependencies: 205
-- Name: role_id_seq; Type: SEQUENCE SET; Schema: fencing; Owner: -
--

SELECT pg_catalog.setval('fencing.role_id_seq', 1, false);


--
-- TOC entry 3009 (class 0 OID 0)
-- Dependencies: 204
-- Name: weapon_weapon_id_seq; Type: SEQUENCE SET; Schema: fencing; Owner: -
--

SELECT pg_catalog.setval('fencing.weapon_weapon_id_seq', 1, true);


--
-- TOC entry 2792 (class 2606 OID 16422)
-- Name: bout_fencer bout_fencer_pk; Type: CONSTRAINT; Schema: fencing; Owner: -
--

ALTER TABLE ONLY fencing.bout_fencer
    ADD CONSTRAINT bout_fencer_pk PRIMARY KEY (bout_id, fencer_id);


--
-- TOC entry 2790 (class 2606 OID 16424)
-- Name: bout bout_pkey; Type: CONSTRAINT; Schema: fencing; Owner: -
--

ALTER TABLE ONLY fencing.bout
    ADD CONSTRAINT bout_pkey PRIMARY KEY (bout_id);


--
-- TOC entry 2794 (class 2606 OID 16426)
-- Name: fencer fencer_pkey; Type: CONSTRAINT; Schema: fencing; Owner: -
--

ALTER TABLE ONLY fencing.fencer
    ADD CONSTRAINT fencer_pkey PRIMARY KEY (fencer_id);


--
-- TOC entry 2802 (class 2606 OID 16562)
-- Name: principal principal_pkey; Type: CONSTRAINT; Schema: fencing; Owner: -
--

ALTER TABLE ONLY fencing.principal
    ADD CONSTRAINT principal_pkey PRIMARY KEY (id);


--
-- TOC entry 2798 (class 2606 OID 16466)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: fencing; Owner: -
--

ALTER TABLE ONLY fencing.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- TOC entry 2800 (class 2606 OID 16567)
-- Name: role uk_bjxn5ii7v7ygwx39et0wawu0q; Type: CONSTRAINT; Schema: fencing; Owner: -
--

ALTER TABLE ONLY fencing.role
    ADD CONSTRAINT uk_bjxn5ii7v7ygwx39et0wawu0q UNIQUE (role);


--
-- TOC entry 2804 (class 2606 OID 16569)
-- Name: principal uk_ob8kqyqqgmefl0aco34akdtpe; Type: CONSTRAINT; Schema: fencing; Owner: -
--

ALTER TABLE ONLY fencing.principal
    ADD CONSTRAINT uk_ob8kqyqqgmefl0aco34akdtpe UNIQUE (email);


--
-- TOC entry 2796 (class 2606 OID 16428)
-- Name: weapon weapon_pkey; Type: CONSTRAINT; Schema: fencing; Owner: -
--

ALTER TABLE ONLY fencing.weapon
    ADD CONSTRAINT weapon_pkey PRIMARY KEY (weapon_id);


--
-- TOC entry 2806 (class 2606 OID 16429)
-- Name: bout_fencer bout_fencer_bout_id_fkey; Type: FK CONSTRAINT; Schema: fencing; Owner: -
--

ALTER TABLE ONLY fencing.bout_fencer
    ADD CONSTRAINT bout_fencer_bout_id_fkey FOREIGN KEY (bout_id) REFERENCES fencing.bout(bout_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 2807 (class 2606 OID 16434)
-- Name: bout_fencer bout_fencer_fencer_id_fkey; Type: FK CONSTRAINT; Schema: fencing; Owner: -
--

ALTER TABLE ONLY fencing.bout_fencer
    ADD CONSTRAINT bout_fencer_fencer_id_fkey FOREIGN KEY (fencer_id) REFERENCES fencing.fencer(fencer_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 2805 (class 2606 OID 16439)
-- Name: bout bout_weapon_id_fkey; Type: FK CONSTRAINT; Schema: fencing; Owner: -
--

ALTER TABLE ONLY fencing.bout
    ADD CONSTRAINT bout_weapon_id_fkey FOREIGN KEY (weapon_id) REFERENCES fencing.weapon(weapon_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 2808 (class 2606 OID 16570)
-- Name: principal_role fk_5k3dviices5fr7560hvc81x4r; Type: FK CONSTRAINT; Schema: fencing; Owner: -
--

ALTER TABLE ONLY fencing.principal_role
    ADD CONSTRAINT fk_5k3dviices5fr7560hvc81x4r FOREIGN KEY (roles_id) REFERENCES fencing.role(id);


--
-- TOC entry 2809 (class 2606 OID 16575)
-- Name: principal_role fk_apcc8lxk2xnug8377fatvbn04; Type: FK CONSTRAINT; Schema: fencing; Owner: -
--

ALTER TABLE ONLY fencing.principal_role
    ADD CONSTRAINT fk_apcc8lxk2xnug8377fatvbn04 FOREIGN KEY (principal_id) REFERENCES fencing.principal(id);


--
-- TOC entry 2949 (class 0 OID 0)
-- Dependencies: 9
-- Name: SCHEMA fencing; Type: ACL; Schema: -; Owner: -
--

GRANT ALL ON SCHEMA fencing TO telescrime;


--
-- TOC entry 2951 (class 0 OID 0)
-- Dependencies: 7
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: -
--

GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- TOC entry 2954 (class 0 OID 0)
-- Dependencies: 235
-- Name: FUNCTION citextin(cstring); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citextin(cstring) TO telescrime;


--
-- TOC entry 2955 (class 0 OID 0)
-- Dependencies: 236
-- Name: FUNCTION citextout(fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citextout(fencing.citext) TO telescrime;


--
-- TOC entry 2956 (class 0 OID 0)
-- Dependencies: 237
-- Name: FUNCTION citextrecv(internal); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citextrecv(internal) TO telescrime;


--
-- TOC entry 2957 (class 0 OID 0)
-- Dependencies: 238
-- Name: FUNCTION citextsend(fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citextsend(fencing.citext) TO telescrime;


--
-- TOC entry 2958 (class 0 OID 0)
-- Dependencies: 224
-- Name: FUNCTION citext(boolean); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citext(boolean) TO telescrime;


--
-- TOC entry 2959 (class 0 OID 0)
-- Dependencies: 223
-- Name: FUNCTION citext(character); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citext(character) TO telescrime;


--
-- TOC entry 2960 (class 0 OID 0)
-- Dependencies: 222
-- Name: FUNCTION citext(inet); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citext(inet) TO telescrime;


--
-- TOC entry 2961 (class 0 OID 0)
-- Dependencies: 225
-- Name: FUNCTION citext_cmp(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citext_cmp(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2962 (class 0 OID 0)
-- Dependencies: 226
-- Name: FUNCTION citext_eq(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citext_eq(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2963 (class 0 OID 0)
-- Dependencies: 227
-- Name: FUNCTION citext_ge(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citext_ge(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2964 (class 0 OID 0)
-- Dependencies: 228
-- Name: FUNCTION citext_gt(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citext_gt(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2965 (class 0 OID 0)
-- Dependencies: 229
-- Name: FUNCTION citext_hash(fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citext_hash(fencing.citext) TO telescrime;


--
-- TOC entry 2966 (class 0 OID 0)
-- Dependencies: 230
-- Name: FUNCTION citext_larger(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citext_larger(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2967 (class 0 OID 0)
-- Dependencies: 231
-- Name: FUNCTION citext_le(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citext_le(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2968 (class 0 OID 0)
-- Dependencies: 232
-- Name: FUNCTION citext_lt(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citext_lt(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2969 (class 0 OID 0)
-- Dependencies: 233
-- Name: FUNCTION citext_ne(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citext_ne(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2970 (class 0 OID 0)
-- Dependencies: 234
-- Name: FUNCTION citext_smaller(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.citext_smaller(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2971 (class 0 OID 0)
-- Dependencies: 240
-- Name: FUNCTION regexp_match(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.regexp_match(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2972 (class 0 OID 0)
-- Dependencies: 239
-- Name: FUNCTION regexp_match(fencing.citext, fencing.citext, text); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.regexp_match(fencing.citext, fencing.citext, text) TO telescrime;


--
-- TOC entry 2973 (class 0 OID 0)
-- Dependencies: 242
-- Name: FUNCTION regexp_matches(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.regexp_matches(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2974 (class 0 OID 0)
-- Dependencies: 241
-- Name: FUNCTION regexp_matches(fencing.citext, fencing.citext, text); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.regexp_matches(fencing.citext, fencing.citext, text) TO telescrime;


--
-- TOC entry 2975 (class 0 OID 0)
-- Dependencies: 243
-- Name: FUNCTION regexp_replace(fencing.citext, fencing.citext, text); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.regexp_replace(fencing.citext, fencing.citext, text) TO telescrime;


--
-- TOC entry 2976 (class 0 OID 0)
-- Dependencies: 244
-- Name: FUNCTION regexp_replace(fencing.citext, fencing.citext, text, text); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.regexp_replace(fencing.citext, fencing.citext, text, text) TO telescrime;


--
-- TOC entry 2977 (class 0 OID 0)
-- Dependencies: 245
-- Name: FUNCTION regexp_split_to_array(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.regexp_split_to_array(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2978 (class 0 OID 0)
-- Dependencies: 246
-- Name: FUNCTION regexp_split_to_array(fencing.citext, fencing.citext, text); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.regexp_split_to_array(fencing.citext, fencing.citext, text) TO telescrime;


--
-- TOC entry 2979 (class 0 OID 0)
-- Dependencies: 248
-- Name: FUNCTION regexp_split_to_table(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.regexp_split_to_table(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2980 (class 0 OID 0)
-- Dependencies: 247
-- Name: FUNCTION regexp_split_to_table(fencing.citext, fencing.citext, text); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.regexp_split_to_table(fencing.citext, fencing.citext, text) TO telescrime;


--
-- TOC entry 2981 (class 0 OID 0)
-- Dependencies: 249
-- Name: FUNCTION replace(fencing.citext, fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.replace(fencing.citext, fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2982 (class 0 OID 0)
-- Dependencies: 250
-- Name: FUNCTION split_part(fencing.citext, fencing.citext, integer); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.split_part(fencing.citext, fencing.citext, integer) TO telescrime;


--
-- TOC entry 2983 (class 0 OID 0)
-- Dependencies: 251
-- Name: FUNCTION strpos(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.strpos(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2984 (class 0 OID 0)
-- Dependencies: 253
-- Name: FUNCTION texticlike(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.texticlike(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2985 (class 0 OID 0)
-- Dependencies: 252
-- Name: FUNCTION texticlike(fencing.citext, text); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.texticlike(fencing.citext, text) TO telescrime;


--
-- TOC entry 2986 (class 0 OID 0)
-- Dependencies: 254
-- Name: FUNCTION texticnlike(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.texticnlike(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2987 (class 0 OID 0)
-- Dependencies: 255
-- Name: FUNCTION texticnlike(fencing.citext, text); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.texticnlike(fencing.citext, text) TO telescrime;


--
-- TOC entry 2988 (class 0 OID 0)
-- Dependencies: 256
-- Name: FUNCTION texticregexeq(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.texticregexeq(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2989 (class 0 OID 0)
-- Dependencies: 257
-- Name: FUNCTION texticregexeq(fencing.citext, text); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.texticregexeq(fencing.citext, text) TO telescrime;


--
-- TOC entry 2990 (class 0 OID 0)
-- Dependencies: 259
-- Name: FUNCTION texticregexne(fencing.citext, fencing.citext); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.texticregexne(fencing.citext, fencing.citext) TO telescrime;


--
-- TOC entry 2991 (class 0 OID 0)
-- Dependencies: 258
-- Name: FUNCTION texticregexne(fencing.citext, text); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.texticregexne(fencing.citext, text) TO telescrime;


--
-- TOC entry 2992 (class 0 OID 0)
-- Dependencies: 260
-- Name: FUNCTION translate(fencing.citext, fencing.citext, text); Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON FUNCTION fencing.translate(fencing.citext, fencing.citext, text) TO telescrime;


--
-- TOC entry 2993 (class 0 OID 0)
-- Dependencies: 198
-- Name: TABLE bout; Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON TABLE fencing.bout TO telescrime;


--
-- TOC entry 2994 (class 0 OID 0)
-- Dependencies: 199
-- Name: SEQUENCE bout_bout_id_seq; Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON SEQUENCE fencing.bout_bout_id_seq TO telescrime;


--
-- TOC entry 2995 (class 0 OID 0)
-- Dependencies: 200
-- Name: TABLE bout_fencer; Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON TABLE fencing.bout_fencer TO telescrime;


--
-- TOC entry 2996 (class 0 OID 0)
-- Dependencies: 201
-- Name: TABLE fencer; Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON TABLE fencing.fencer TO telescrime;


--
-- TOC entry 2997 (class 0 OID 0)
-- Dependencies: 202
-- Name: SEQUENCE fencer_fencer_id_seq; Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON SEQUENCE fencing.fencer_fencer_id_seq TO telescrime;


--
-- TOC entry 2998 (class 0 OID 0)
-- Dependencies: 208
-- Name: TABLE principal; Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON TABLE fencing.principal TO telescrime;


--
-- TOC entry 2999 (class 0 OID 0)
-- Dependencies: 207
-- Name: SEQUENCE principal_id_seq; Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON SEQUENCE fencing.principal_id_seq TO telescrime;


--
-- TOC entry 3000 (class 0 OID 0)
-- Dependencies: 209
-- Name: TABLE principal_role; Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON TABLE fencing.principal_role TO telescrime;


--
-- TOC entry 3001 (class 0 OID 0)
-- Dependencies: 206
-- Name: TABLE role; Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON TABLE fencing.role TO telescrime;


--
-- TOC entry 3002 (class 0 OID 0)
-- Dependencies: 205
-- Name: SEQUENCE role_id_seq; Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON SEQUENCE fencing.role_id_seq TO telescrime;


--
-- TOC entry 3003 (class 0 OID 0)
-- Dependencies: 203
-- Name: TABLE weapon; Type: ACL; Schema: fencing; Owner: -
--

GRANT ALL ON TABLE fencing.weapon TO telescrime WITH GRANT OPTION;


--
-- TOC entry 3004 (class 0 OID 0)
-- Dependencies: 204
-- Name: SEQUENCE weapon_weapon_id_seq; Type: ACL; Schema: fencing; Owner: -
--

GRANT UPDATE ON SEQUENCE fencing.weapon_weapon_id_seq TO telescrime;
GRANT SELECT,USAGE ON SEQUENCE fencing.weapon_weapon_id_seq TO telescrime WITH GRANT OPTION;


--
-- TOC entry 1776 (class 826 OID 16449)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: -; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE lukas GRANT SELECT,USAGE ON SEQUENCES  TO telescrime WITH GRANT OPTION;


--
-- TOC entry 1777 (class 826 OID 16450)
-- Name: DEFAULT PRIVILEGES FOR TYPES; Type: DEFAULT ACL; Schema: -; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE lukas GRANT ALL ON TYPES  TO telescrime WITH GRANT OPTION;


--
-- TOC entry 1778 (class 826 OID 16451)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: -; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE lukas GRANT ALL ON FUNCTIONS  TO telescrime WITH GRANT OPTION;


--
-- TOC entry 1779 (class 826 OID 16452)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: -
--

ALTER DEFAULT PRIVILEGES FOR ROLE lukas GRANT ALL ON TABLES  TO telescrime WITH GRANT OPTION;


-- Completed on 2018-12-06 23:01:00

--
-- PostgreSQL database dump complete
--

