package de.tlscrm.model;
// Generated 18-Nov-2018 16:12:17 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BoutFencerId generated by hbm2java
 */
@Embeddable
public class BoutFencerId implements java.io.Serializable {

	private int boutId;
	private int fencerId;

	public BoutFencerId() {}

	public BoutFencerId(final int boutId, final int fencerId) {
		this.boutId = boutId;
		this.fencerId = fencerId;
	}

	@Column(name = "bout_id", nullable = false)
	public int getBoutId() {
		return this.boutId;
	}

	public void setBoutId(final int boutId) {
		this.boutId = boutId;
	}

	@Column(name = "fencer_id", nullable = false)
	public int getFencerId() {
		return this.fencerId;
	}

	public void setFencerId(final int fencerId) {
		this.fencerId = fencerId;
	}

	@Override
	public boolean equals(final Object other) {
		if ((this == other)) {
			return true;
		}
		if ((other == null)) {
			return false;
		}
		if (!(other instanceof BoutFencerId)) {
			return false;
		}
		final BoutFencerId castOther = (BoutFencerId) other;

		return (this.getBoutId() == castOther.getBoutId())
		        && (this.getFencerId() == castOther.getFencerId());
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBoutId();
		result = 37 * result + this.getFencerId();
		return result;
	}

}
