package de.tlscrm.model;
// Generated 18-Nov-2018 16:12:17 by Hibernate Tools 5.2.11.Final

import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BoutFencer generated by hbm2java
 *
 * @author ltegethoff (modified after generation)
 */
@Entity
@Table(name = "bout_fencer", schema = "fencing")
public class BoutFencer implements java.io.Serializable {

	private BoutFencerId id;
	private Bout bout;
	private Fencer fencer;
	private short hits;

	public BoutFencer() {}

	public BoutFencer(final BoutFencerId id, final Bout bout, final Fencer fencer,
	        final short hits) {
		this.id = id;
		this.bout = bout;
		this.fencer = fencer;
		this.hits = hits;
	}

	@EmbeddedId

	@AttributeOverride(name = "boutId", column = @Column(name = "bout_id", nullable = false))
	@AttributeOverride(name = "fencerId", column = @Column(name = "fencer_id", nullable = false))
	public BoutFencerId getId() {
		return this.id;
	}

	public void setId(final BoutFencerId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bout_id", nullable = false, insertable = false, updatable = false)
	public Bout getBout() {
		return this.bout;
	}

	public void setBout(final Bout bout) {
		this.bout = bout;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fencer_id", nullable = false, insertable = false, updatable = false)
	public Fencer getFencer() {
		return this.fencer;
	}

	public void setFencer(final Fencer fencer) {
		this.fencer = fencer;
	}

	@Column(name = "hits", nullable = false)
	public short getHits() {
		return this.hits;
	}

	public void setHits(final short hits) {
		this.hits = hits;
	}

}
