package de.tlscrm.model;
// Generated 18-Nov-2018 16:12:17 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fencer generated by hbm2java
 */
@Entity
@Table(name = "fencer", schema = "fencing")
public class Fencer implements java.io.Serializable {

	private int fencerId;
	private String name;
	private Set<BoutFencer> boutFencers = new HashSet<>(0);

	public Fencer() {}

	public Fencer(final int fencerId) {
		this.fencerId = fencerId;
	}

	public Fencer(final int fencerId, final String name, final Set<BoutFencer> boutFencers) {
		this.fencerId = fencerId;
		this.name = name;
		this.boutFencers = boutFencers;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "fencer_id", unique = true, nullable = false)
	public int getFencerId() {
		return this.fencerId;
	}

	public void setFencerId(final int fencerId) {
		this.fencerId = fencerId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(final String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fencer")
	public Set<BoutFencer> getBoutFencers() {
		return this.boutFencers;
	}

	public void setBoutFencers(final Set<BoutFencer> boutFencers) {
		this.boutFencers = boutFencers;
	}

}
