package de.tlscrm.model;
// Generated 02-Dec-2018 18:52:51 by Hibernate Tools 5.2.11.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Principal generated by hbm2java
 *
 * @author ltegethoff (modified after generation)
 */
@NamedQuery(name = Principal.FIND_BY_EMAIL,
      query = "select p from Principal p where p.email = :email")
@NamedQuery(name = Principal.COUNT_EMAIL,
      query = "select count(p.email) from Principal p where p.email = :email")
@Entity
@Table(name = "principal", schema = "fencing",
      uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Principal implements java.io.Serializable {

   public static final String FIND_BY_EMAIL = "principal.findbyemail";
   public static final String COUNT_EMAIL = "principal.countemail";

   private long id;
   private String email;
   private String firstname;
   private String lastname;
   private String password;
   private Set<Role> roles = new HashSet<>(0);

   public Principal() {}


   public Principal(final long id) {
      this.id = id;
   }

   public Principal(final long id, final String email, final String firstname,
         final String lastname, final String password, final Set<Role> roles) {
      this.id = id;
      this.email = email;
      this.firstname = firstname;
      this.lastname = lastname;
      this.password = password;
      this.roles = roles;
   }

   @Id
   @GeneratedValue(strategy = GenerationType.IDENTITY)
   @Column(name = "id", unique = true, nullable = false)
   public long getId() {
      return this.id;
   }

   public void setId(final long id) {
      this.id = id;
   }


   @Column(name = "email", unique = true)
   public String getEmail() {
      return this.email;
   }

   public void setEmail(final String email) {
      this.email = email;
   }


   @Column(name = "firstname")
   public String getFirstname() {
      return this.firstname;
   }

   public void setFirstname(final String firstname) {
      this.firstname = firstname;
   }


   @Column(name = "lastname")
   public String getLastname() {
      return this.lastname;
   }

   public void setLastname(final String lastname) {
      this.lastname = lastname;
   }


   @Column(name = "password")
   public String getPassword() {
      return this.password;
   }

   public void setPassword(final String password) {
      this.password = password;
   }

   @ManyToMany(fetch = FetchType.EAGER)
   public Set<Role> getRoles() {
      return this.roles;
   }

   public void setRoles(final Set<Role> roles) {
      this.roles = roles;
   }



}


