package de.tlscrm.model;
// Generated 02-Dec-2018 18:52:51 by Hibernate Tools 5.2.11.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Role generated by hbm2java
 *
 * @author ltegethoff (modified after generation)
 */
@Entity
@Table(name = "role", schema = "fencing",
      uniqueConstraints = @UniqueConstraint(columnNames = "role"))
public class Role implements java.io.Serializable {


	private long id;
	private String role;

	public Role() {}


	public Role(final long id, final String role) {
		this.id = id;
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(final long id) {
		this.id = id;
	}


	@Column(name = "role", unique = true, nullable = false)
	public String getRole() {
		return this.role;
	}

	public void setRole(final String role) {
		this.role = role;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (id ^ (id >>> 32));
		result = prime * result + ((role == null) ? 0 : role.hashCode());
		return result;
	}


	@Override
	public boolean equals(final Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Role other = (Role) obj;
		if (id != other.id) {
			return false;
		}
		if (role == null) {
			if (other.role != null) {
				return false;
			}
		} else if (!role.equals(other.role)) {
			return false;
		}
		return true;
	}

}
