package de.tlscrm.model;
// Generated 02-Dec-2018 18:52:51 by Hibernate Tools 5.2.11.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Role generated by hbm2java
 *
 * @author ltegethoff (modified after generation)
 */
@Entity
@Table(name = "role", schema = "fencing",
        uniqueConstraints = @UniqueConstraint(columnNames = "role"))
public class Role implements java.io.Serializable {


	private long id;
	private String role;

	public Role() {}


	public Role(final long id, final String role) {
		this.id = id;
		this.role = role;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(final long id) {
		this.id = id;
	}


	@Column(name = "role", unique = true, nullable = false)
	public String getRole() {
		return this.role;
	}

	public void setRole(final String role) {
		this.role = role;
	}
}
