package de.tlscrm.model;
// Generated 18-Nov-2018 16:12:17 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Weapon generated by hbm2java
 */
@Entity
@Table(name = "weapon", schema = "fencing")
public class Weapon implements java.io.Serializable {

	private int weaponId;
	private String name;
	private Set<Bout> bouts = new HashSet<>(0);

	public Weapon() {}

	public Weapon(final int weaponId) {
		this.weaponId = weaponId;
	}

	public Weapon(final int weaponId, final String name, final Set<Bout> bouts) {
		this.weaponId = weaponId;
		this.name = name;
		this.bouts = bouts;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "weapon_id", unique = true, nullable = false)
	public int getWeaponId() {
		return this.weaponId;
	}

	public void setWeaponId(final int weaponId) {
		this.weaponId = weaponId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(final String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "weapon")
	public Set<Bout> getBouts() {
		return this.bouts;
	}

	public void setBouts(final Set<Bout> bouts) {
		this.bouts = bouts;
	}

}
